language: java
sudo: true
dist: trusty
jdk: openjdk11
before_install:
  - chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: 34a3c213-75c2-46cd-9d70-c4103564e3c8
  app:
    rsoi: fanorona-jva-server